<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Discord Webhook Tutorial</title>
  </head>
  <body>
    <button onclick="sendMessage()">Send</button>
  </body>\
  

  <script>
    function sendMessage() {
      var request = new XMLHttpRequest();
      request.open("POST", "https://discordapp.com/api/webhooks/712577237605416981/spMyOy45FWiC8fUrWNXN_ABvZ_gSoDrBVVqPu7KcAdRLCRBOQB_Y322LLk4k-i7XucGC");

      request.setRequestHeader('Content-type', 'application/json');

      var params = {
        username: "Winston",
        avatar_url: "",
        content: "Do not say the n word."
      }

      request.send(JSON.stringify(params));
    }
  </script>
</html>
